export const test_items = [{
        id: 1,
        title: '스프린트1 이슈1',
        content: '내용',
        author: 'sang-gyeong',
        milestone: '스프린트1',
        status: 'opened',
        labels: [{
                name: 'Bug',
                color: '#bfd4f2',
            },
            {
                name: 'front-end',
                color: '#e3a5aa',
            },
        ],
        assignees: ['a'],
        time: '2020-10-28',
    },
    {
        id: 2,
        title: '스프린트2 이슈2',
        content: '내용2',
        author: 'b',
        milestone: '스프린트2',
        status: 'opened',
        labels: [{
                name: 'Bug',
                color: '#bfd4f2',
            },
            {
                name: 'high-priority',
                color: '#e3a5aa',
            },
        ],
        assignees: ['sang-gyeong'],
        time: '2020-10-28',
    },
    {
        id: 3,
        title: '스프린트3 이슈2',
        content: '내용2',
        author: 'b',
        milestone: '스프린트3',
        status: 'opened',
        labels: [],
        assignees: [],
        time: '2020-10-28',
    },
    {
        id: 4,
        title: '스프린트2 이슈2',
        content: '내용2',
        author: 'a',
        milestone: '스프린트2',
        status: 'closed',
        labels: [{
                name: 'back-end',
                color: '#bfd4f2',
            },
            {
                name: 'feature',
                color: '#e3a5aa',
            },
        ],
        assignees: ['sang-gyeong', 'a'],
        time: '2020-10-28',
    },
    {
        id: 5,
        title: '이슈10',
        content: '내용2',
        author: 'sang-gyeong',
        milestone: null,
        status: 'closed',
        labels: [{
                name: 'bug',
                color: '#bfd4f2',
            },
            {
                name: 'front-end',
                color: '#e3a5aa',
            },
        ],
        assignees: [],
        time: '2020-10-28',
    },
    {
        id: 6,
        title: '이슈12 입니다',
        content: '내용2',
        author: 'sang-gyeong',
        milestone: null,
        status: 'opened',
        labels: [],
        assignees: ['a', 'sang-gyeong'],
        time: '2020-10-28',
    },
];