export default {
    SELECT_ALL: 'SELECT_ALL',
    DESELECT_ALL: 'DESELECT_ALL',
    CHECKED_UPDATE: 'CHECKED_UPDATE',

    UPDATE_FILTER: 'UPDATE_FILTER',
    GET_ISSUES: 'GET_ISSUES',
    GET_ISSUES_SUCCESS: 'GET_ISSUES_SUCCESS',
    GET_ISSUES_ERROR: 'GET_ISSUES_ERROR',

    GET_LABELS: 'GET_LABELS',
    GET_LABELS_SUCCESS: 'GET_LABELS_SUCCESS',
    GET_LABELS_ERROR: 'GET_LABELS_ERROR',

    GET_MILESTONES: 'GET_MILESTONES',
    GET_MILESTONES_SUCCESS: 'GET_MILESTONES_SUCCESS',
    GET_MILESTONES_ERROR: 'GET_MILESTONES_ERROR',

    SET_USER: 'SET_USER',
    SET_USER_SUCCESS: 'SET_USER_SUCCESS',
    SET_USER_ERROR: 'SET_USER_ERROR',

    GET_USERS: 'GET_USERS',
    GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
    GET_USERS_ERROR: 'GET_USERS_ERROR'
}